---
title: "Examine Life Expectancy"
author: "Richard Ressler"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Here, I re-examine the analysis of Oeppen and Vaupel (2002).
Section 001 more even more and more comments
new stuff


# my Life Expectancy Analysis
- I have added some comments here for my branch

```{r}
library(tidyverse)
library(gapminder)
data(gapminder_unfiltered)
```

- Set the data
```{r}
# new comment
gapminder_unfiltered %>% 
  group_by(year) %>% 
  filter(lifeExp == max(lifeExp)) %>% 
  ungroup() %>% 
  select(year, country, lifeExp) %>% 
  arrange(year) ->
  sumdat
```
new plot
```{r}
 sumdat %>%
      ggplot(aes(x = year, y = lifeExp)) +
      geom_point(aes(color = country)) +
      geom_point(pch = 1) + 
      theme_bw() +
      geom_smooth(method = "lm", se = FALSE) +
      xlab("Year") +
      ylab("Maximum Life Expectancy") +
      scale_color_discrete(name = "Country")

```
